name: Dart Analyze
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Analyze code
        run: dart analyze --fatal-infos
      - name: Install dependencies
        run: dart pub get
      - name: Outdated dependencies
        run: dart pub outdated
      - name: Run tests
        run: dart test